### ISSUE TITLE
Broken cuda-10.1.243 container

### ISSUE THREAD

**Issue by mdavis36** [rse-ops/docker-images#48]
The `cuda-10.1.243` container is broken when trying to build code with `nvcc`. The `gcc` version the container is using targets `gcc@9.3.0`. `nvcc10` doesn't support `gcc` past `8.X`.

**Comment by davidbeckingsale** [comment]
Thanks for reporting this @mdavis36

**Comment by vsoch** [comment]
@davidbeckingsale I can give a shot at fixing this - what is the recommended action?

**Comment by davidbeckingsale** [comment]
I think just putting `gcc@8.something` and making sure that was the default would be a good fix. Alternative might be to use an older Ubuntu base like 18.

**Comment by vsoch** [comment]
So you mean hard coding it into the Dockerfile for all images?

**Comment by vsoch** [comment]
@davidbeckingsale this is a dynamically generated matrix and gcc is not a variable (it's whatever is provided in the container) https://github.com/rse-ops/docker-images/blob/main/ubuntu/cuda/uptodate.yaml.

Why is nvcc only supporting gcc that is so old? Lame.

**Comment by davidbeckingsale** [comment]
Because it's an old NVCC :'(

**Comment by vsoch** [comment]
:ghost: boo! :laughing:
